---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: infra
  namespace: user0
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/lalyos/flux-bb/

